openapi: 3.0.3
info:
  title: Sync Savings API Specification
  x-logo:
    url: ./sync_logo.png
    backgroundColor: '#FFFFFF'
  description: |
    # Introduction

    Welcome to the Sync Savings API, providing access to the Sync Savings Platform.

    ℹ️ Embedded savings is the integration of cash savings products into other digital applications without the need to redirect users to the underlying financial institution. Embedded financial services enable providers to offer seamless access to relevant financial products at the point of intent, and thus drive engagement and value to customers.

    🔑 Authentication: The API requires authentication using API keys included in request headers (see authorize)

    Should you have any queries on the standards implemented or the capability of our services, please do let us know by emailing us at **contact@sync-savings.com**

    # Overview

    The Sync Savings API provides a set of RESTful, JSON-based APIs that can be used to create and manage savings for your users.

    # Security

    We store only the required information to be able to provide your users with a savings account, all data is encrypted at rest and in transit by TLS 1.2+. Authentication is provided by AWS's Cognito product which restricts access to the API.
    
    User data is segregated by Distributor so that it is only accessible to clients from the relevant Distributor and with a token bearing the correct level of permission.

    # Authentication

    We use the [OAuth 2.0 Client Credentials](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow) flow for authentication.
      The `clientId` and `clientSecret` can be exchanged for an accessToken, this can be reused until it expires. Typically this is after 10 minutes,
      the time that the token will expire is listed in the `"exp"` field of the access token.

      Details of how to obtain an access token will be included when issuing the `clientId` and `clientSecret`. All requests must include the access token in the `Authorization` header.
    
    # Pagination

    All of our Search endpoints, e.g. [searching transactions by Account ID](#tag/Transactions/paths/~1transactions/get) accept optional `limit` and `page` query parameters.
    
    By default the `limit` parameter is set to `10` and the `page` is set to `1`.

servers:
  - url: https://api.sandbox.sync-savings.com
    description: Sandbox API
  - url: https://api.sync-savings.com
    description: Production API (uses live data)

security:
  - oauth2: []

tags:
  - name: Savers
    description: |
      Savers are Distributors' customers, Savers want to open an Account to save money.

  - name: Products
    description: | 
      Products represent the types of savings accounts available with Banks.

  - name: Accounts
    description: |
      Accounts are owned by a Saver, they are the representation in Sync's system of the Saver's bank account.

  - name: Transactions
    description: |
      Transactions are owned by an Account, they are the representation in Sync's system of cash movements in the Saver's bank account.

  - name: Commitments
    description: |
      Commitments are the Saver's instruction of how much they want to contribute to their Account.

  - name: Reconciliations
    description: |
      Reconciliations are instructions to Sync on how to distribute a consolidated payment in.
  - name: Webhooks
    $ref: 'webhooks.yaml'

paths:
  /savers:
    $ref: 'savers.yaml#/paths/~1savers'
  /savers/{saverId}:
    $ref: 'savers.yaml#/paths/~1savers~1{saverId}'
  /products:
    $ref: 'products.yaml#/paths/~1products'
  /accounts:
    $ref: 'accounts.yaml#/paths/~1accounts'
  /accounts/{accountId}:
    $ref: 'accounts.yaml#/paths/~1accounts~1{accountId}'
  /transactions:
    $ref: 'transactions.yaml#/paths/~1transactions'
  /transactions/{transactionId}:
    $ref: 'transactions.yaml#/paths/~1transactions~1{transactionId}'
  /commitments:
    $ref: 'commitments.yaml#/paths/~1commitments'
  /commitments/{commitmentId}:
    $ref: 'commitments.yaml#/paths/~1commitments~1{commitmentId}'
  /reconciliations:
    $ref: 'reconciliations.yaml#/paths/~1reconciliations'
  /reconciliations/{reconciliationId}:
    $ref: 'reconciliations.yaml#/paths/~1reconciliations~1{reconciliationId}'

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://sync-savings.auth.eu-west-2.amazoncognito.com/oauth2/token'
          scopes: {}